services:
  - type: web
    name: legal-rag-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 "Legal Assistance RAG Chatbot.app:app"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
